# 17) Fetching data from an API

In [1]:
import pandas as pd 
import requests

## Making a request call to API

In [2]:
requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

## Saving the response that we got from API

In [3]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [4]:
# We got 4 key-value pairs , out of that 4 , we want 'results'
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,159.693,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.706,26485
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",147.498,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.700,20105
2,False,/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,109.598,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.577,12131
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,111.549,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,15535
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,63.768,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.545,8382
5,False,/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",148.368,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-04-18,Spirited Away,False,8.500,16134
6,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",49.283,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.535,4405
7,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,145.235,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.500,32236
8,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",102.929,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.509,17788
9,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,97.740,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.506,17008
10,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,104.634,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.490,11118
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",102.210,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.488,27395
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,163.723,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.482,23646
13,False,/fzkLKtZCkYSDzxoqntE5KgIqvzk.jpg,"[12, 36, 28, 18, 10749, 53]",1084736,fr,Le Comte de Monte-Cristo,Edmond Dantes becomes the target of a sinister...,51.650,/aHRUsFln97FlIdsvYKFT3z5ubYE.jpg,2024-06-28,The Count of Monte-Cristo,False,8.474,308
14,False,/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,108.736,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.475,26900
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,103.835,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.465,8385
16,False,/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",97.349,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.464,12563
17,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,es,Cosas imposibles,"After the death of her abusive husband, Matild...",18.072,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,Impossible Things,False,8.459,379
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,49.303,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.459,3560
19,False,/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.055,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.458,5326

In [8]:
pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,159.693,8.706,26485
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,147.498,8.700,20105
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,109.598,8.577,12131
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,111.549,8.566,15535
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,63.768,8.545,8382
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-04-18,148.368,8.500,16134
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,49.283,8.535,4405
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,145.235,8.500,32236
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,102.929,8.509,17788
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,97.740,8.506,17008
10,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,104.634,8.490,11118
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,102.210,8.488,27395
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-01,163.723,8.482,23646
13,1084736,The Count of Monte-Cristo,Edmond Dantes becomes the target of a sinister...,2024-06-28,51.650,8.474,308
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,108.736,8.475,26900
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,103.835,8.465,8385
16,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,97.349,8.464,12563
17,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,18.072,8.459,379
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,49.303,8.459,3560
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.055,8.458,5326

In [5]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [6]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,159.693,8.706,26485
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,147.498,8.700,20105
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,109.598,8.577,12131
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,111.549,8.566,15535
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,63.768,8.545,8382
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-04-18,148.368,8.500,16134
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,49.283,8.535,4405
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,145.235,8.500,32236
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,102.929,8.509,17788
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,97.740,8.506,17008
10,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,104.634,8.490,11118
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,102.210,8.488,27395
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-01,163.723,8.482,23646
13,1084736,The Count of Monte-Cristo,Edmond Dantes becomes the target of a sinister...,2024-06-28,51.650,8.474,308
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,108.736,8.475,26900
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,103.835,8.465,8385
16,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,97.349,8.464,12563
17,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,18.072,8.459,379
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,49.303,8.459,3560
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.055,8.458,5326

## Appending the entire data using pd.concat() fn.

In [7]:
data = pd.DataFrame()

In [8]:
data

Empty DataFrame
Columns: []
Index: []

In [11]:
for i in range(1,429) :
    response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    data=pd.concat([data,df],ignore_index=True)

In [12]:
data

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,159.693,8.706,26485
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,147.498,8.700,20105
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,109.598,8.577,12131
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,111.549,8.566,15535
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,63.768,8.545,8382
...,...,...,...,...,...,...,...
8755,441384,The Beach Bum,An irreverent comedy about the misadventures o...,2019-03-21,16.762,5.641,483
8756,336011,White Girl,"Summer, New York City. A college girl falls ha...",2016-09-02,22.904,5.600,448
8757,23823,Wrong Turn 3: Left for Dead,A group of people find themselves trapped in t...,2009-10-20,102.328,5.641,1115
8758,336455,Viral,Following the outbreak of a virus that wipes o...,2016-02-18,13.789,5.600,498
8759,624808,Love Wedding Repeat,While trying to make his sister's wedding day ...,2020-04-10,17.982,5.600,688

# Saving the dataset

In [13]:
data.to_csv('movies_tmdb.csv')

## Also see about RapidAPI