# 26. Encoding Categorical Data

In [167]:
import numpy as np 
import pandas as pd

In [169]:
df=pd.read_csv("customer.csv")

# purchased column - we suggest a product after the user bought first product

In [171]:
df.sample(5)

    age  gender   review education purchased
16   59    Male     Poor        UG       Yes
8    65  Female  Average        UG        No
11   74    Male     Good        UG       Yes
20   57  Female  Average    School       Yes
49   25  Female     Good        UG        No

In [173]:
df=df.iloc[:,2:]

# gender column is nominal and we need to do One Hot Encoding 
# review, education - Ordinal 
# purchased - label encoding

In [175]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [177]:
df.shape

(50, 3)

### Before we proceed further we need to split our data into train and test

In [180]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [182]:
X_train

     review education
47     Good        PG
45     Poor        PG
31     Poor    School
21  Average        PG
48     Good        UG
41     Good        PG
29  Average        UG
9      Good        UG
20  Average    School
32  Average        UG
24  Average        PG
49     Good        UG
16     Poor        UG
15     Poor        UG
18     Good    School
38     Good    School
12     Poor    School
17     Poor        UG
44  Average        UG
1      Poor        UG
40     Good    School
28     Poor    School
14     Poor        PG
42     Good        PG
2      Good        PG
33     Good        PG
36     Good        UG
6      Good    School
8   Average        UG
3      Good        PG
4   Average        UG
25     Good    School
46     Poor        PG
37  Average        PG
39     Poor        PG
22     Poor        PG
27     Poor        PG
19     Poor        PG
13  Average    School
35     Poor    School

### Importing Ordinal Encoder class

In [185]:
from sklearn.preprocessing import OrdinalEncoder

In [187]:
# Values are given from min to max order (always) 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [189]:
oe.fit(X_train)

# fit - learn/determines what to assign 
# transform - actually assigns the value

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [191]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [197]:
X_train

# We can see that the categorical data are converted to numerical (with ordering)

array([[2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 0.]])

In [199]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Importing Label Encoder class

In [205]:
from sklearn.preprocessing import LabelEncoder

In [207]:
le = LabelEncoder()

In [209]:
le.fit(y_train)

LabelEncoder()

In [211]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [213]:
y_train = le.transform(y_train) 
y_test = le.transform(y_test)

In [215]:
y_train

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1])